// ============================================================
// VictorMeet — Languages Dictionary & Translations
// ============================================================

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'pt', name: 'Português (Portuguese)' },
  { code: 'de', name: 'Deutsch (German)' }
];

export const TRANSLATIONS = {
  en: {
    tagline: "Talk to Strangers!",
    premiumNotice: "Connect with users by gender & region! Get 50% off today.",
    upgradeNow: "Upgrade Now",
    heroTitle: "VictorMeet: Talk to Strangers!",
    heroText: "VictorMeet is a great way to meet new friends. When you use VictorMeet, we pick someone else at random so you can have a one-on-one chat.",
    usersOnline: "users online right now",
    chooseName: "Choose a Name / Nickname",
    namePlaceholder: "Enter nickname to start...",
    enterAge: "Enter your Age",
    agePlaceholder: "Enter your age (e.g. 18)...",
    safetyTitle: "⚠️ Safety Formalities",
    agreeAge: "I am 18 years or older, or 13+ with parental consent.",
    agreeTerms: "I accept VictorMeet's",
    terms: "Terms",
    and: "&",
    privacy: "Privacy Policy",
    startTexting: "💬 Text",
    startVideo: "📹 Video",
    selectCamera: "Select Camera Source:",
    detectingCameras: "Detecting cameras...",
    startMatchingHint: "Click Start to begin matching",
    matchingOverlayText: "Matching...",
    systemWelcome: 'System: Click "Start" below to begin talking to a random stranger.',
    systemMatched: "You're now chatting with a random stranger. Say hi!",
    systemLeft: "Stranger has disconnected.",
    startBtn: "Start",
    sendBtn: "Send",
    placeholderMsg: "Type a message...",
    funnyTagsTitle: "Popular & Funny Filters (Optional):",
    donateLabel: "❤️ Donate"
  },
  hi: {
    tagline: "अजनबियों से बात करें!",
    premiumNotice: "लिंग और क्षेत्र के आधार पर उपयोगकर्ताओं से जुड़ें! आज ही 50% की छूट पाएं।",
    upgradeNow: "अभी अपग्रेड करें",
    heroTitle: "VictorMeet: अजनबियों से बात करें!",
    heroText: "VictorMeet नए दोस्तों से मिलने का एक शानदार तरीका है। जब आप VictorMeet का उपयोग करते हैं, तो हम किसी अन्य को यादृच्छिक रूप से चुनते हैं ताकि आप आमने-सामने बातचीत कर सकें।",
    usersOnline: "उपयोगकर्ता अभी ऑनलाइन हैं",
    chooseName: "एक नाम / उपनाम चुनें",
    namePlaceholder: "शुरू करने के लिए उपनाम दर्ज करें...",
    enterAge: "अपनी उम्र दर्ज करें",
    agePlaceholder: "अपनी उम्र दर्ज करें (जैसे 18)...",
    safetyTitle: "⚠️ सुरक्षा औपचारिकताएं",
    agreeAge: "मैं 18 वर्ष या उससे अधिक का हूँ, या माता-पिता की सहमति से 13+ हूँ।",
    agreeTerms: "मैं स्वीकार करता हूँ VictorMeet के",
    terms: "नियम",
    and: "और",
    privacy: "गोपनीयता नीति",
    startTexting: "💬 चैट (टेक्स्ट)",
    startVideo: "📹 वीडियो चैट",
    selectCamera: "कैमरा स्रोत चुनें:",
    detectingCameras: "कैमरों का पता लगाया जा रहा है...",
    startMatchingHint: "मिलान शुरू करने के लिए स्टार्ट पर क्लिक करें",
    matchingOverlayText: "मिलान हो रहा है...",
    systemWelcome: 'सिस्टम: किसी यादृच्छिक अजनबी से बात करना शुरू करने के लिए नीचे "स्टार्ट" पर क्लिक करें।',
    systemMatched: "अब आप एक यादृच्छिक अजनबी से चैट कर रहे हैं। नमस्ते कहें!",
    systemLeft: "अजनबी डिस्कनेक्ट हो गया है।",
    startBtn: "स्टार्ट",
    sendBtn: "भेजें",
    placeholderMsg: "संदेश लिखें...",
    funnyTagsTitle: "लोकप्रिय और मजेदार फ़िल्टर (वैकल्पिक):",
    donateLabel: "❤️ दान करें"
  },
  ta: {
    tagline: "அந்நியர்களுடன் பேசுங்கள்!",
    premiumNotice: "பாலினம் & பிராந்தியத்தின் அடிப்படையில் பயனர்களுடன் இணையுங்கள்! இன்று 50% தள்ளுபடி பெறுக.",
    upgradeNow: "இப்போது மேம்படுத்துக",
    heroTitle: "VictorMeet: அந்நியர்களுடன் பேசுங்கள்!",
    heroText: "VictorMeet புதிய நண்பர்களை சந்திக்க ஒரு சிறந்த வழியாகும். நீங்கள் VictorMeet ஐப் பயன்படுத்தும் போது, நாங்கள் ஒருவரைத் தேர்ந்தெடுத்து உங்களுடன் பேச வைப்போம்.",
    usersOnline: "பயனர்கள் இப்போது ஆன்லைனில் உள்ளனர்",
    chooseName: "ஒரு பெயர் / புனைப்பெயரைத் தேர்ந்தெடுக்கவும்",
    namePlaceholder: "தொடங்குவதற்கு புனைப்பெயரை உள்ளிடவும்...",
    enterAge: "உங்கள் வயதை உள்ளிடவும்",
    agePlaceholder: "உங்கள் வயதை உள்ளிடவும் (எ.கா. 18)...",
    safetyTitle: "⚠️ பாதுகாப்பு விதிமுறைகள்",
    agreeAge: "எனக்கு 18 வயது அல்லது அதற்கு மேல் ஆகிறது, அல்லது பெற்றோர் அனுமதியுடன் 13+ ஆகிறது.",
    agreeTerms: "நான் VictorMeet இன்",
    terms: "விதிமுறைகள்",
    and: "மற்றும்",
    privacy: "தனியுரிமைக் கொள்கையை ஏற்கிறேன்",
    startTexting: "💬 உரை (Text)",
    startVideo: "📹 வீடியோ",
    selectCamera: "கேமரா மூலத்தைத் தேர்ந்தெடுக்கவும்:",
    detectingCameras: "கேமராக்கள் கண்டறியப்படுகின்றன...",
    startMatchingHint: "இணைக்கத் தொடங்க 'ஸ்டார்ட்' கிளிக் செய்யவும்",
    matchingOverlayText: "இணைக்கப்படுகிறது...",
    systemWelcome: 'சிஸ்டம்: அந்நியருடன் பேசத் தொடங்க கீழே உள்ள "ஸ்டார்ட்" பொத்தானை கிளிக் செய்யவும்.',
    systemMatched: "நீங்கள் இப்போது ஒரு அந்நியருடன் அரட்டையடிக்கிறீர்கள். ஹலோ சொல்லுங்கள்!",
    systemLeft: "அந்நியர் துண்டிக்கப்பட்டார்.",
    startBtn: "ஸ்டார்ட்",
    sendBtn: "அனுப்பு",
    placeholderMsg: "செய்தியை உள்ளிடவும்...",
    funnyTagsTitle: "பிரபலமான & வேடிக்கையான வடிப்பான்கள் (விருப்பத்தேர்வு):",
    donateLabel: "❤️ ஆதரவு"
  },
  es: {
    tagline: "¡Habla con extraños!",
    premiumNotice: "¡Conéctate con usuarios por género y región! Obtén un 50% de descuento hoy.",
    upgradeNow: "Actualizar ahora",
    heroTitle: "VictorMeet: ¡Habla con extraños!",
    heroText: "VictorMeet es una excelente manera de conocer nuevos amigos. Cuando usas VictorMeet, elegimos a otra persona al azar para que puedas tener un chat uno a uno.",
    usersOnline: "usuarios en línea ahora",
    chooseName: "Elige un Nombre / Apodo",
    namePlaceholder: "Ingresa un apodo para comenzar...",
    enterAge: "Ingresa tu Edad",
    agePlaceholder: "Ingresa tu edad (ej. 18)...",
    safetyTitle: "⚠️ Formalidades de Seguridad",
    agreeAge: "Tengo 18 años o más, o 13+ con consentimiento paterno.",
    agreeTerms: "Acepto las",
    terms: "Condiciones",
    and: "y la",
    privacy: "Política de Privacidad de VictorMeet",
    startTexting: "💬 Texto",
    startVideo: "📹 Video",
    selectCamera: "Seleccionar cámara:",
    detectingCameras: "Detectando cámaras...",
    startMatchingHint: "Haz clic en Iniciar para comenzar a buscar",
    matchingOverlayText: "Buscando pareja...",
    systemWelcome: 'Sistema: Haz clic en "Iniciar" abajo para comenzar a hablar con un extraño al azar.',
    systemMatched: "Ahora estás chateando con un extraño. ¡Dile hola!",
    systemLeft: "El extraño se ha desconectado.",
    startBtn: "Iniciar",
    sendBtn: "Enviar",
    placeholderMsg: "Escribe un mensaje...",
    funnyTagsTitle: "Filtros populares y divertidos (Opcional):",
    donateLabel: "❤️ Donar"
  },
  fr: {
    tagline: "Parlez à des inconnus !",
    premiumNotice: "Connectez-vous avec des utilisateurs par sexe et par région ! -50% aujourd'hui.",
    upgradeNow: "Mettre à niveau",
    heroTitle: "VictorMeet: Parlez à des inconnus !",
    heroText: "VictorMeet est un excellent moyen de rencontrer de nouveaux amis. Lorsque vous utilisez VictorMeet, nous choisissons quelqu'un d'autre au hasard pour un chat en tête-à-tête.",
    usersOnline: "utilisateurs en ligne",
    chooseName: "Choisissez un nom / pseudo",
    namePlaceholder: "Entrez votre pseudo...",
    enterAge: "Entrez votre âge",
    agePlaceholder: "Entrez votre âge (ex: 18)...",
    safetyTitle: "⚠️ Formalités de sécurité",
    agreeAge: "J'ai 18 ans ou plus, ou 13+ avec consentement parental.",
    agreeTerms: "J'accepte les",
    terms: "Conditions",
    and: "et la",
    privacy: "Politique de confidentialité",
    startTexting: "💬 Texte",
    startVideo: "📹 Vidéo",
    selectCamera: "Choisir la caméra :",
    detectingCameras: "Détection des caméras...",
    startMatchingHint: "Cliquez sur Commencer pour lancer le jumelage",
    matchingOverlayText: "Jumelage...",
    systemWelcome: 'Système : Cliquez sur "Commencer" ci-dessous pour parler à un inconnu.',
    systemMatched: "Vous discutez avec un inconnu. Dites bonjour !",
    systemLeft: "L'inconnu s'est déconnecté.",
    startBtn: "Commencer",
    sendBtn: "Envoyer",
    placeholderMsg: "Écrivez un message...",
    funnyTagsTitle: "Filtres populaires et drôles (Optionnel):",
    donateLabel: "❤️ Faire un don"
  },
  ar: {
    tagline: "تحدث مع الغرباء!",
    premiumNotice: "تواصل مع المستخدمين حسب الجنس والمنطقة! احصل على خصم 50٪ اليوم.",
    upgradeNow: "ترقية الآن",
    heroTitle: "VictorMeet: تحدث مع الغرباء!",
    heroText: "يعد VictorMeet طريقة رائعة للتعرف على أصدقاء جدد. عند استخدام VictorMeet، سنختار شخصًا آخر عشوائيًا لتبدأ معه محادثة فردية.",
    usersOnline: "المستخدمين متصلين الآن",
    chooseName: "اختر اسمًا أو لقبًا",
    namePlaceholder: "أدخل الاسم المستعار للبدء...",
    enterAge: "أدخل عمرك",
    agePlaceholder: "أدخل عمرك (مثال: 18)...",
    safetyTitle: "⚠️ إجراءات السلامة",
    agreeAge: "أنا بعمر 18 سنة أو أكثر، أو 13+ مع موافقة الوالدين.",
    agreeTerms: "أوافق على",
    terms: "الشروط",
    and: "و",
    privacy: "سياسة الخصوصية لـ VictorMeet",
    startTexting: "💬 نصي",
    startVideo: "📹 فيديو",
    selectCamera: "اختر الكاميرا:",
    detectingCameras: "جارٍ الكشف عن الكاميرات...",
    startMatchingHint: "انقر فوق ابدأ للبدء في البحث عن شريك",
    matchingOverlayText: "جاري البحث...",
    systemWelcome: 'النظام: انقر فوق "ابدأ" أدناه لبدء التحدث مع غريب عشوائي.',
    systemMatched: "أنت الآن تدردش مع غريب عشوائي. ألقِ التحية!",
    systemLeft: "لقد غادر الغريب المحادثة.",
    startBtn: "ابدأ",
    sendBtn: "إرسال",
    placeholderMsg: "اكتب رسالة...",
    funnyTagsTitle: "عناصر التصفية الشائعة والمضحكة (اختياري):",
    donateLabel: "❤️ تبرع"
  },
  pt: {
    tagline: "Converse com estranhos!",
    premiumNotice: "Conecte-se com usuários por gênero e região! Ganhe 50% de desconto hoje.",
    upgradeNow: "Melhorar Agora",
    heroTitle: "VictorMeet: Converse com estranhos!",
    heroText: "O VictorMeet é uma ótima maneira de fazer novos amigos. Quando você usa o VictorMeet, nós escolhemos outra pessoa aleatoriamente para uma conversa individual.",
    usersOnline: "usuários online agora",
    chooseName: "Escolha um Nome / Apelido",
    namePlaceholder: "Digite um apelido para começar...",
    enterAge: "Digite sua Idade",
    agePlaceholder: "Digite sua idade (ex: 18)...",
    safetyTitle: "⚠️ Formalidades de Segurança",
    agreeAge: "Tenho 18 anos ou mais, ou 13+ com consentimento dos pais.",
    agreeTerms: "Aceito os",
    terms: "Termos",
    and: "e a",
    privacy: "Política de Privacidade do VictorMeet",
    startTexting: "💬 Texto",
    startVideo: "📹 Vídeo",
    selectCamera: "Selecionar câmera:",
    detectingCameras: "Detectando câmeras...",
    startMatchingHint: "Clique em Iniciar para começar a parear",
    matchingOverlayText: "Pareando...",
    systemWelcome: 'Sistema: Clique em "Iniciar" abaixo para começar a falar com um estranho.',
    systemMatched: "Você está conversando com um estranho. Diga olá!",
    systemLeft: "O estranho se desconectou.",
    startBtn: "Iniciar",
    sendBtn: "Enviar",
    placeholderMsg: "Digite uma mensagem...",
    funnyTagsTitle: "Filtros populares e engraçados (Opcional):",
    donateLabel: "❤️ Doar"
  },
  de: {
    tagline: "Sprich mit Fremden!",
    premiumNotice: "Verbinde dich mit Nutzern nach Geschlecht & Region! Erhalte heute 50% Rabatt.",
    upgradeNow: "Jetzt upgraden",
    heroTitle: "VictorMeet: Sprich mit Fremden!",
    heroText: "VictorMeet ist eine großartige Möglichkeit, neue Freunde zu finden. Wenn du VictorMeet nutzt, wählen wir zufällig jemanden aus, mit dem du ein Einzelgespräch führen kannst.",
    usersOnline: "Benutzer jetzt online",
    chooseName: "Wähle einen Namen / Spitznamen",
    namePlaceholder: "Spitznamen eingeben...",
    enterAge: "Gib dein Alter ein",
    agePlaceholder: "Gib dein Alter ein (z.B. 18)...",
    safetyTitle: "⚠️ Sicherheitsformalitäten",
    agreeAge: "Ich bin 18 Jahre oder älter, oder 13+ mit Zustimmung der Eltern.",
    agreeTerms: "Ich akzeptiere die",
    terms: "Bedingungen",
    and: "und die",
    privacy: "Datenschutzerklärung von VictorMeet",
    startTexting: "💬 Text",
    startVideo: "📹 Video",
    selectCamera: "Kamera auswählen:",
    detectingCameras: "Kameras werden gescannt...",
    startMatchingHint: "Klicke auf Start, um die Suche zu beginnen",
    matchingOverlayText: "Verbindung wird hergestellt...",
    systemWelcome: 'System: Klicke unten auf "Start", um das Gespräch mit einem Fremden zu beginnen.',
    systemMatched: "Du chattest jetzt mit einem Fremden. Sag Hallo!",
    systemLeft: "Der Fremde hat die Verbindung getrennt.",
    startBtn: "Start",
    sendBtn: "Senden",
    placeholderMsg: "Nachricht eingeben...",
    funnyTagsTitle: "Beliebte & lustige Filter (Optional):",
    donateLabel: "❤️ Spenden"
  }
};
